### ISSUE TITLE
Rename Default app modules

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/CopyrightFixer#1]
The project should be have a next structure:

- [x] rename The library and executable file
```
├── src
│   ├── Example // rename to CFixer
│   └── Library    // rename to CopyrighFixer
│    
└── tests              

```

- [x] rename exampletest to cfixertest

**Comment by EndrII** [comment]
@IgorekLoschinin check our [contribution](https://github.com/QuasarApp/Guidelines/blob/master/Contribution.md) roles please .

**Comment by EndrII** [comment]
@IgorekLoschinin check our [developing](https://github.com/QuasarApp/Guidelines/blob/master/Developming.md) guide please.

**Comment by IgorekLoschinin** [comment]
1) Changed the structure of the project, the names of the directories: Example (CFixer), Library (CopyrighFixer).
2) Changing the name exampletest -> cfixertest.

**Comment by EndrII** [comment]
Please do not close issue before successful merge PR.

**Comment by EndrII** [comment]
You forget change name of the cfixer tool 
https://github.com/QuasarApp/CopyrightFixer/blob/task_15/src/CFixer/CMakeLists.txt#L10
