### ISSUE TITLE
Create A simple class for printing "Hello world " message

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/CopyrightFixer#15]
# This is teaching task for learning c++ project structures.

## Status
This project have a 3 components:
1. CopyrightFixer Library. (This is main library with all functions of this project)
2. CFixer tool (This is main tool for using all functions of this project.
3. And CopyrightFixer tests. This is test for testing all functions of the main library.

## Work Plan
Create a simple **Bar** class with one **foo** method, invoke the foo method from cfixer tool and print message from foo.

## Create the Bar class.
Class location : CopyrighFixer/src/CopyrighFixer/CopyrighFixer (cpp and h files. for create use qtcreator )

Class should be contains the method foo. the foo method should be return **bar**  value with QString type. 

## Use your Bar class in CFixer tool.

* include your bar.h header in the main.cpp of the CFixer tool.
* in the main function create variable of the Bar class and invoke the foo method.
* The value of the foo method should be  assigned into QString variable.
* uses any known functions print the value of QString variable.

## Testing your Bar class.

In the cfixertest test create a method for testing your Foo method of the Bar class. 
You can create a Bar class and invoke the foo method from this.
And compare the return value with  right value using the [QVERIFY](https://doc.qt.io/qt-5/qtest.html#QVERIFY)

**Comment by IgorekLoschinin** [comment]
Done!
